export const qaEn = {
 recognitionNone:'No candidate', recognitionCandidate:'Candidate', recognitionHolding:'Holding', recognitionConfirmed:'Confirmed',
 title:'Team camera QA', intro:'Run this on the actual demo device. No images, video or landmarks are recorded or uploaded. Use device labels, not patient information.',
 fast:'Fast demo check · 6 gestures', extended:'Extended check · both hands', mode:'Check mode', device:'Device name', browser:'Browser', camera:'Camera', hand:'Hand being tested', light:'Lighting', distance:'Distance',
 good:'Good', medium:'Medium', poor:'Poor', close:'Close', normal:'Normal', far:'Far', Left:'Left', Right:'Right', laptop:'Laptop', front:'Front', rear:'Rear', unknown:'Unknown',
 startCamera:'Start QA camera', stopCamera:'Stop camera', start:'Start attempt', finish:'Finish attempt', save:'Save review & next gesture', discard:'Discard unsaved attempt',
 instruction:'Remove your hand, start an attempt, then show the gesture. For HELP, first bend your pinky, check the correction, then straighten it and hold.',
 alignmentHelp:'The labels identify the actual tracked fingertips. Compare them with your hand. Model handedness is shown as reported, without changing recognition.',
 expected:'Expected gesture', candidate:'Detected candidate', confirmed:'Confirmed gestures', fps:'Analyzed FPS', visible:'Hand-visible frames', corrections:'Corrections shown', detected:'Model handedness', detectedCamera:'Reported camera facing',
 review:'Human review', correct:'Was the intended gesture recognized correctly?', alignment:'Was the finger highlight aligned with your actual finger?', false:'Did any false confirmation occur?',
 yes:'Yes', no:'No', na:'Not applicable', choose:'Choose…', notes:'Notes (no patient details)', summary:'Camera test summary', attempts:'Attempts saved', gestures:'Normal-condition checks', success:'Confirmed as intended',
 falseCount:'False confirmations', alignCount:'Finger alignment', meanTime:'Mean candidate-to-confirmation', meanFps:'Mean analyzed FPS', ready:'READY', needsReview:'NEEDS REVIEW',
 summaryHelp:'Manual demo readiness for this run only, not recognition accuracy or medical validation. Readiness needs all six gestures in good light at normal distance, no failed attempts, and an aligned HELP pinky correction. Extended mode needs both hands.',
 json:'Download JSON', csv:'Download CSV', newRun:'Start a new run', confirmReset:'Discard this local QA run? Download results first if you need them.',
 noResults:'No manual results recorded yet.', cameraNeeded:'Start the real camera to begin.', interrupted:'Camera interrupted. Review this attempt as failed and retry.',
 storage:'Results remain in this page until you download them. Reloading clears this QA run.', back:'Back to diagnostics', tracking:'Tracking available', noHand:'No hand detected',
 elapsed:'Attempt duration', helpCheck:'HELP correction alignment', build:'Build', frozen:'Context is saved with each attempt. Finish the current review before changing conditions.',
};
export const qaRu: Record<keyof typeof qaEn,string> = {
 recognitionNone:'Нет кандидата', recognitionCandidate:'Кандидат', recognitionHolding:'Удержание', recognitionConfirmed:'Подтверждено',
 title:'Проверка камеры для команды', intro:'Запустите на устройстве для демонстрации. Изображения, видео и точки руки не записываются и не передаются. Указывайте устройство, без данных пациентов.',
 fast:'Быстрая проверка · 6 жестов', extended:'Расширенная · обе руки', mode:'Режим проверки', device:'Название устройства', browser:'Браузер', camera:'Камера', hand:'Проверяемая рука', light:'Освещение', distance:'Расстояние',
 good:'Хорошее', medium:'Среднее', poor:'Плохое', close:'Близко', normal:'Обычное', far:'Далеко', Left:'Левая', Right:'Правая', laptop:'Ноутбук', front:'Фронтальная', rear:'Задняя', unknown:'Неизвестно',
 startCamera:'Включить камеру для проверки', stopCamera:'Остановить камеру', start:'Начать попытку', finish:'Завершить попытку', save:'Сохранить и перейти дальше', discard:'Отменить несохранённую попытку',
 instruction:'Уберите руку, начните попытку, затем покажите жест. Для HELP сначала согните мизинец, проверьте подсказку, затем выпрямите его и удерживайте жест.',
 alignmentHelp:'Подписи отмечают отслеживаемые кончики пальцев. Сравните их со своей рукой. Сторона руки показана так, как её определила модель, без изменения распознавания.',
 expected:'Ожидаемый жест', candidate:'Предполагаемый жест', confirmed:'Подтверждённые жесты', fps:'Обработанных кадров / с', visible:'Кадры с рукой', corrections:'Показанные подсказки', detected:'Сторона руки по модели', detectedCamera:'Тип камеры по данным устройства',
 review:'Оценка человеком', correct:'Нужный жест распознан верно?', alignment:'Подсветка совпала с нужным пальцем на вашей руке?', false:'Было ложное подтверждение?',
 yes:'Да', no:'Нет', na:'Не применимо', choose:'Выберите…', notes:'Заметки (без данных пациентов)', summary:'Итоги проверки камеры', attempts:'Сохранено попыток', gestures:'Проверки в обычных условиях', success:'Нужный жест подтверждён',
 falseCount:'Ложные подтверждения', alignCount:'Совпадение подсветки', meanTime:'Среднее время подтверждения', meanFps:'Средняя частота обработки', ready:'ГОТОВО', needsReview:'НУЖНА ПРОВЕРКА',
 summaryHelp:'Готовность к демо только по этой проверке, не точность распознавания и не медицинская валидация. Нужны все шесть жестов при хорошем свете на обычном расстоянии, без неудачных попыток, и верная подсветка мизинца для HELP. Расширенный режим требует обе руки.',
 json:'Скачать JSON', csv:'Скачать CSV', newRun:'Начать новую проверку', confirmReset:'Удалить результаты этой локальной проверки? Сначала скачайте их, если они нужны.',
 noResults:'Результатов ручной проверки пока нет.', cameraNeeded:'Сначала включите реальную камеру.', interrupted:'Камера прервана. Отметьте попытку неудачной и повторите.',
 storage:'Результаты хранятся на странице до скачивания. Обновление страницы сбросит эту проверку.', back:'К диагностике', tracking:'Рука отслеживается', noHand:'Рука не найдена',
 elapsed:'Длительность попытки', helpCheck:'Подсветка коррекции HELP', build:'Сборка', frozen:'Условия сохраняются с каждой попыткой. Завершите оценку перед изменением условий.',
};
